spring.application.name=EndList

spring.datasource.url=jdbc:postgresql://localhost:5432/endlist
spring.datasource.username=endlist
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
